version: '3.8'

services:
  # API (NestJS)
  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    container_name: anime-tracker-api
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - db

  # Frontend (React + Vite)
  web:
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY}
    container_name: anime-tracker-web
    restart: unless-stopped
    ports:
      - "5173:80" # Nginx serve na porta 80 dentro do contêiner
    networks:
      - app-network
    depends_on:
      - api

  # Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: anime-tracker-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
